id = "kedi"
name = "Kedi"
version = "0.2.0"
schema_version = 1
authors = ["Mert <mert@kedi-lang.org>"]
description = "Kedi language support for Zed via Tree-sitter queries and Kedi LSP."
repository = "https://github.com/kedi-lang/kedi-zed"
snippets = ["./snippets/kedi.json"]

[[capabilities]]
kind = "process:exec"
command = "*"
args = ["**"]

[language_servers.kedi-lsp]
name = "kedi-lsp"
languages = ["Kedi"]

[language_servers.kedi-lsp.language_ids]
"Kedi" = "kedi"

[language_servers.kedi-embedded-python]
name = "kedi-embedded-python"
languages = ["Kedi"]

[language_servers.kedi-embedded-python.language_ids]
"Kedi" = "kedi"

[grammars.kedi]
repository = "https://github.com/kedi-lang/tree-sitter-kedi"
rev = "fa8e6a9665e1ea9c73927bd8b30f85d6dc828061"
