id = "kedi"
name = "Kedi"
version = "0.3.0"
schema_version = 1
authors = ["Mert <mert@kedi-lang.org>"]
description = "Kedi language support for Zed via Tree-sitter queries and Kedi LSP."
repository = "https://github.com/kedi-lang/kedi-zed"
snippets = ["./snippets/kedi.json"]

[[capabilities]]
kind = "process:exec"
command = "*"
args = ["**"]

[language_servers.kedi-lsp]
name = "kedi-lsp"
languages = ["Kedi"]

[language_servers.kedi-lsp.language_ids]
"Kedi" = "kedi"

[language_servers.kedi-embedded-python]
name = "kedi-embedded-python"
languages = ["Kedi"]

[language_servers.kedi-embedded-python.language_ids]
"Kedi" = "kedi"

[language_servers.kedi-python-docstrings]
name = "kedi-python-docstrings"
languages = ["Python"]

[language_servers.kedi-python-docstrings.language_ids]
"Python" = "python"

[grammars.kedi]
repository = "https://github.com/kedi-lang/tree-sitter-kedi"
rev = "653415c03aa8b4a1155e002903478d1462e376c0"
